# Generated by Django 4.2.5 on 2023-11-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
